swagger: "2.0"
info:
  title: Fulfillorder
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: shanepeckham@live.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /order/:
    post:
      tags:
      - order
      description: process order POST
      operationId: OrderController.Process Order
      parameters:
      - in: body
        name: body
        description: body for order content
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      responses:
        "200":
          description: '{string} models.Order.ID'
        "403":
          description: body is empty
definitions:
  models.Order:
    title: Order
    required:
    - ID
    - EmailAddress
    - Product
    - Total
    - Status
    type: object
    properties:
      EmailAddress:
        description: Email address of the customer
        type: string
      ID:
        description: CosmoDB ID - will be autogenerated
        type: string
      Product:
        description: Product ordered by the customer
        type: string
      Status:
        description: Order Status
        type: string
      Total:
        description: Order total
        type: number
        format: double
tags:
- name: order
  description: |
    Operations about order
